services:
  - type: web
    name: workly
    env: node
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://workly-zd8z.onrender.com